"""
Django settings for gaia project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import json
from pathlib import Path
from sys import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if platform == "linux":
    #GDAL_LIBRARY_PATH = '/anaconda/envs/gaia/lib/libgdal.so'
    GDAL_LIBRARY_PATH = os.getenv("GDAL_LIBRARY_PATH", "/opt/conda/envs/gaia/lib/libgdal.so")
    #GEOS_LIBRARY_PATH = '/anaconda/envs/gaia/lib/geos_c.so'
    SPATIALITE_LIBRARY_PATH = '/opt/conda/envs/gaia/lib/mod_spatialite.so'

elif platform == "win32":
    USER_HOME = os.path.expanduser("~")
    CONDA_PREFIX = os.environ.get("CONDA_PREFIX", "")    
    GDAL_LIBRARY_PATH = os.path.join(CONDA_PREFIX, 'Library', 'bin', 'gdal.dll')
    GEOS_LIBRARY_PATH = os.path.join(CONDA_PREFIX, 'Library', 'bin', 'geos_c.dll')
    SPATIALITE_LIBRARY_PATH = os.path.join(CONDA_PREFIX, 'Library', 'bin','mod_spatialite.dll')
else:
    print("YOUR PLATFORM IS NOT SUPPORTED AT THIS TIME!")

SECRETS_FILE = os.path.join(BASE_DIR, 'gaia/secrets.json')

# SECURITY WARNING: keep the secret key used in production secret!
with open(SECRETS_FILE) as f:
    secrets = json.load(f)

SECRET_KEY = secrets['DJANGO_KEY']

# Basic Django Configuration
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.auth',
    'debug_toolbar',
    'animal',
    'adminsortable2',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'two_factor',
    #'django_q',
    #'corsheaders',
]
YUBIKEY_AVAILABLE = False

# -----------------------------------------------------------------------------
# Celery Configuration
# -----------------------------------------------------------------------------
from kombu import Exchange, Queue

# Redis and Broker Configuration
REDIS_URL = secrets.get('REDIS_URL', 'redis://redis:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Queue Configuration
CELERY_TASK_DEFAULT_QUEUE = 'celery'
CELERY_TASK_DEFAULT_EXCHANGE = 'celery'
CELERY_TASK_CREATE_MISSING_QUEUES = True
CELERY_TASK_QUEUES = (
    Queue('celery', 
          Exchange('celery', type='direct', durable=True),
          routing_key='celery',
          queue_arguments={'x-queue-type': 'classic', 'x-message-ttl': 7200000}),  # 2 hour TTL
    Queue('imagery',
          Exchange('imagery', type='direct', durable=True),
          routing_key='imagery',
          queue_arguments={'x-queue-type': 'classic', 'x-message-ttl': 7200000})
)

# Task Routes - All routing rules consolidated here
CELERY_TASK_ROUTES = {
    'gaia.celery.*': {'queue': 'celery'},
    'gaia.imagery.*': {'queue': 'imagery'},
    'animal.tasks.imagery_tasks.*': {'queue': 'imagery'},
    'animal.tasks.tasks.*': {'queue': 'celery'}
}

# Worker Settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1     # Prevent worker starvation
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 4000000  # Restart workers at 4GB memory usage
CELERY_WORKER_DIRECT = False              # Enable event system for Flower monitoring
CELERY_WORKER_SEND_TASK_EVENTS = True     # Enable task events for monitoring
CELERY_SEND_EVENTS = True                 # Enable event publishing
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = TIME_ZONE

# Task Execution Settings
CELERY_TASK_TRACK_STARTED = True          # Enable task progress tracking
CELERY_TASK_TIME_LIMIT = 7200             # 2 hour timeout for long-running tasks
CELERY_TASK_SOFT_TIME_LIMIT = 6900        # Soft timeout 5 minutes before hard timeout
CELERY_TASK_ACKS_LATE = True              # Only acknowledge tasks after completion
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Requeue tasks if worker dies
CELERY_TASK_DEFAULT_RATE_LIMIT = '10/m'   # Default rate limit for tasks
CELERY_TASK_REMOTE_TRACEBACKS = True      # Include remote tracebacks in errors
CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_QUEUE_MAX_PRIORITY = 10       # Enable task priorities
CELERY_TASK_DEFAULT_PRIORITY = 5          # Default task priority
CELERY_ACCEPT_CONTENT = ['json']

# Result Backend Settings
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_COMPRESSION = 'gzip'        # Compress results to save Redis memory
CELERY_RESULT_EXPIRES = 7200              # Results expire after 2 hours (matching task timeout)
CELERY_RESULT_PERSISTENT = True           # Persist results in Redis
CELERY_RESULT_EXTENDED = True             # Store extended task result info
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'retry_policy': {
        'timeout': 5.0,
        'max_retries': 10,
        'interval_start': 0,
        'interval_step': 0.2,
        'interval_max': 0.5,
    }
}

# Broker Connection Settings
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 20
CELERY_BROKER_CONNECTION_TIMEOUT = 60
CELERY_BROKER_HEARTBEAT = 120
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 7200,    # Match task time limit (2 hours)
    'queue_order_strategy': 'priority'
}

# Redis Connection Pool Settings
CELERY_REDIS_MAX_CONNECTIONS = 20         # Limit connections per worker
CELERY_REDIS_SOCKET_TIMEOUT = 30
CELERY_REDIS_SOCKET_CONNECT_TIMEOUT = 30
CELERY_REDIS_SOCKET_KEEPALIVE = True
CELERY_REDIS_RETRY_ON_TIMEOUT = True

# Task Error Handling
CELERY_TASK_EAGER_PROPAGATES = True       # Propagate chain errors in eager mode
CELERY_CHORD_UNLOCK_MAX_RETRIES = 5       # Maximum retries for unlocking chords

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'animal.middleware.TwoFactorEnforcementMiddleware',  # Re-enabled - 2FA enforcement
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# to turn on debug toolbar, set DEBUG = TRUE and uncommon INTERNAL_IPS and DEBUG_TOOLBAR_CONFIG
DEBUG = False
# INTERNAL_IPS = ['127.0.0.1']
# DEBUG_TOOLBAR_CONFIG = {
#     "SHOW_TOOLBAR_CALLBACK": lambda request: True,
# }
RESULTS_CACHE_SIZE = 1000
ALLOWED_HOSTS = [
                'localhost',
                    ]


if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')  # Add WhiteNoise middleware only when not in debug mode

ROOT_URLCONF = 'gaia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',
                 BASE_DIR / 'animal/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gaia.context_processors.environment',
                'gaia.context_processors.build_date',
                'animal.context_processors.yubikey_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'gaia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.spatialite',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS': {
            'timeout': 60,
        },
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG' if secrets.get('LOG_LEVEL', 'INFO').upper() == 'DEBUG' else 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'verbose',
        },
        'db_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django_sqlite.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['db_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'animal': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'animal.views.flower': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'animal.views.flower_proxy_views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGOUT_REDIRECT_URL = '/account/login/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "static/uswds",
]

# Enable WhiteNoise storage for static files (only for dev environments without a reverse-proxy)
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AZURE_STORAGE_ACCOUNT_NAME = ''
AZURE_STORAGE_ACCOUNT_KEY = secrets['AZURE_KEY']
AZURE_CONTAINER_NAME = 'data'


# Avoid CSRF verfication failures
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8080',  # Add the origin used in your requests
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Email server configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = secrets.get('EMAIL_SERVER', 'smtp.gmail.com')  # Default to 'smtp.gmail.com' if not in secrets
EMAIL_PORT = int(secrets.get('EMAIL_PORT', 587))  # Default to 587 for TLS
EMAIL_USE_TLS = True  # Use TLS for secure email
EMAIL_HOST_USER = secrets.get('EMAIL_USERNAME', '')
EMAIL_HOST_PASSWORD = secrets.get('EMAIL_PASSWORD', '')

# USGS EarthExplorer API credentials
USGS_USERNAME = secrets.get('USGS_USERNAME', '')
USGS_TOKEN = secrets.get('USGS_TOKEN', '')

# Email server configuration for testing
# EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR, "sent_mail")
# print("EMAIL_BACKEND:", EMAIL_BACKEND)
# print("EMAIL_HOST:", EMAIL_HOST)
# print("EMAIL_PORT:", EMAIL_PORT)
# print("EMAIL_USE_TLS:", EMAIL_USE_TLS)
# print("EMAIL_HOST_USER:", EMAIL_HOST_USER)

DEFAULT_FROM_EMAIL = 'no-reply@noaa.gov'

# Two-Factor Authentication Settings
TWO_FACTOR_PATCH_ADMIN = True
TWO_FACTOR_CALL_GATEWAY = None
TWO_FACTOR_SMS_GATEWAY = None

# Available two-factor authentication methods
TWO_FACTOR_ENABLED_METHODS = [
    'generator',  # TOTP (Time-based One-Time Password)
    'yubikey',    # YubiKey hardware tokens
]

# Login URLs - updated for two-factor auth
LOGIN_URL = 'two_factor:login'
LOGIN_REDIRECT_URL = '/'

# OTP settings
OTP_TOTP_ISSUER = 'GAIA - NOAA Fisheries'

# YubiKey OTP Configuration (DISABLED - using passkeys instead)
# You can get these from https://upgrade.yubico.com/getapikey/
# Leave as None to use Yubico's default validation servers
# OTP_YUBIKEY_CLIENT_ID = secrets.get('YUBIKEY_CLIENT_ID', None)
# OTP_YUBIKEY_SECRET_KEY = secrets.get('YUBIKEY_SECRET_KEY', None)

# WebAuthn/FIDO2 Configuration
WEBAUTHN_RP_ID = os.environ.get('WEBAUTHN_RP_ID', 'localhost')
WEBAUTHN_RP_NAME = 'GAIA - NOAA Fisheries'
# Allow both localhost and localhost:8000 for development
WEBAUTHN_ORIGIN = os.environ.get('WEBAUTHN_ORIGIN', 'http://localhost')

# For production, you should set these environment variables:
# WEBAUTHN_RP_ID=yourdomain.com
# WEBAUTHN_ORIGIN=https://yourdomain.com

# OTP Throttling settings - make setup much more forgiving
# Setting a high throttle factor to allow many attempts before blocking
OTP_THROTTLE_FACTOR = 10    # Allow many more attempts before blocking
OTP_TOTP_TOLERANCE = 5      # Allow ±5 time periods (150 seconds window)

# Enable more lenient token validation for setup
# This helps with clock synchronization issues during initial setup
import time
OTP_TOTP_SYNC_TIME_OVERRIDE = None

# Additional Two-Factor settings
TWO_FACTOR_REMEMBER_COOKIE_AGE = 86400  # Remember device for 24 hours (24 * 60 * 60 seconds)
TWO_FACTOR_CALL_GATEWAY = None
TWO_FACTOR_SMS_GATEWAY = None

# 2FA Enforcement Settings
# Set to True to require all users to have 2FA enabled
# Set to False to make 2FA optional for all users (except where explicitly required)
ENFORCE_TWO_FACTOR_AUTH = getattr(os.environ, 'ENFORCE_TWO_FACTOR_AUTH', 'False').lower() == 'true'

# Set to True to require 2FA only for users with NOAA.gov email addresses
# This setting is independent of ENFORCE_TWO_FACTOR_AUTH
ENFORCE_TWO_FACTOR_AUTH_NOAA = getattr(os.environ, 'ENFORCE_TWO_FACTOR_AUTH_NOAA', 'False').lower() == 'true'

# Flower monitoring basic auth credentials
# Priority: secrets.json (if key added later) then environment variable
FLOWER_BASIC_AUTH = secrets.get('FLOWER_BASIC_AUTH') or os.environ.get('FLOWER_BASIC_AUTH')
FLOWER_INTERNAL_URL = secrets.get('FLOWER_INTERNAL_URL') or os.environ.get('FLOWER_INTERNAL_URL')

# Database Repair Configuration
DB_REPAIR_ARTIFACT_DIR = BASE_DIR / "var" / "db_repair"
DB_REPAIR_SOFT_LINKS = BASE_DIR / "gaia" / "soft_links.yaml"