# Generated by Django 5.2.1 on 2025-06-03 13:03

from django.db import migrations

trigger_sql = """
CREATE TRIGGER adjudicate_trigger
AFTER UPDATE ON animal_annotations
BEGIN
    UPDATE animal_pointsofinterest 
    SET final_classification_id = (
        SELECT classification_id 
        FROM (
            SELECT classification_id, COUNT(*) as count
            FROM animal_annotations
            WHERE poi_id = NEW.poi_id
            GROUP BY classification_id
            HAVING COUNT(*) >= 3
            LIMIT 1
        )
    ),
    final_review_date = date('now')
    WHERE id = NEW.poi_id
    AND EXISTS (
        SELECT 1
        FROM animal_annotations
        WHERE poi_id = NEW.poi_id
        GROUP BY classification_id
        HAVING COUNT(*) >= 3
        LIMIT 1
    );
END;
"""

revert_sql = """
DROP TRIGGER IF EXISTS adjudicate_trigger;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(trigger_sql, reverse_sql=revert_sql),
    ]
