# Generated by Django 5.2.3 on 2025-06-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_add_adjudicate_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='date_image_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
