# Generated by Django 5.2.3 on 2025-06-17 13:50

import django.db.models.deletion
from django.db import migrations, models

def create_first_project(apps, schema_editor):
    Project = apps.get_model('animal', 'Project')
    Project.objects.create(
        label='North Atlantic Right Whales in Cape Cod Bay 2020-2024',
        value='narw_capecod_2020_2024',
        description='This project compares very high-resolution satellite imagery and aerial survey data for detecting North Atlantic right whales (Eubalaena glacialis) in Cape Cod Bay between 2020 and 2024.'
    )

def set_existing_poi_project(apps, schema_editor):
    POI = apps.get_model('animal', 'PointsOfInterest')
    POI.objects.all().update(project=1)

# Add reverse operations for the RunPython operations
def reverse_create_first_project(apps, schema_editor):
    Project = apps.get_model('animal', 'Project')
    Project.objects.filter(value='projectname').delete()

def reverse_set_existing_poi_project(apps, schema_editor):
    # When reverting, we don't need to update the project field
    # The field will be dropped as part of the migration reversal
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_annotations_date_pointsofinterest_date_image_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pointsofinterest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.project'),
        ),

        migrations.RunPython(create_first_project, reverse_create_first_project),
        migrations.RunPython(set_existing_poi_project, reverse_set_existing_poi_project),
    ]