# Generated by Django 5.2.3 on 2025-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_project_pointsofinterest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
