# Generated by Django 5.2.3 on 2025-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_alter_project_description_alter_project_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='label',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.CharField(max_length=75),
        ),
    ]
