# Generated by Django 5.2.3 on 2025-07-01 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_alter_project_label_alter_project_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishnet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(blank=True, max_length=39, null=True)),
                ('cell', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
