# Generated by Django 5.2.4 on 2025-07-09 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_fishnet_project_fishnetreviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order of categories')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['category', 'order', 'label']},
        ),
        migrations.AddField(
            model_name='classification',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sorting order within Classification category'),
        ),
        migrations.AddField(
            model_name='classification',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group name for categorizing classifications', null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.category'),
        ),
    ]
