# Generated by Django 5.2.4 on 2025-07-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0009_category_alter_classification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group name for categorizing classifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_order', to='animal.category'),
        ),
    ]
