# Generated by Django 5.2.4 on 2025-07-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0012_projectaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
