# Generated by Django 5.2.4 on 2025-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='sensor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
