# Generated by Django 5.2.5 on 2025-08-15 12:47

import django.db.models.deletion
from django.db import migrations, models
from django.core.management import call_command
import os


def load_species_locations_fixture(apps, schema_editor):
    """
    Create Target rows and Species_Locations mappings.

    Uses apps.get_model instead of loaddata to avoid FK timing issues
    during test DB creation. Species_Locations rows are only created
    when their referenced AOI and Target rows exist — in a fresh test
    DB where no AOIs have been loaded, this is a safe no-op.

    Target data:
        id=9:  Eubalaena glacialis  (N. Atlantic right whale)
        id=10: Eubalaena japonica   (N. Pacific right whale)
    """
    Target = apps.get_model('animal', 'Target')
    AreaOfInterest = apps.get_model('animal', 'AreaOfInterest')
    Species_Locations = apps.get_model('animal', 'Species_Locations')

    narw, _ = Target.objects.get_or_create(
        id=9,
        defaults={'value': 'Eubalaena glacialis',
                  'label': 'N. Atlantic right whale'},
    )
    nprw, _ = Target.objects.get_or_create(
        id=10,
        defaults={'value': 'Eubalaena japonica',
                  'label': 'N. Pacific right whale'},
    )

    # Only create mappings when referenced AOIs exist.
    # In production: AOIs are already loaded, mappings are created.
    # In test DB: no AOIs exist, nothing to map — safe to skip.
    mappings = [(aoi_id, narw) for aoi_id in [6, 15, 50, 124]] + \
               [(aoi_id, nprw) for aoi_id in [23, 24, 25, 26]]

    for aoi_id, target in mappings:
        if AreaOfInterest.objects.filter(id=aoi_id).exists():
            Species_Locations.objects.get_or_create(
                aoi_id=aoi_id, species=target,
            )


def remove_species_locations_data(apps, schema_editor):
    """Remove all species locations data for reverse migration"""
    Species_Locations = apps.get_model('animal', 'Species_Locations')
    Species_Locations.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0014_pointsofinterest_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.RemoveField(
            model_name='areaofinterest',
            name='requestor',
        ),
        migrations.CreateModel(
            name='Species_Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aoi', models.ForeignKey(help_text='Area of Interest', on_delete=django.db.models.deletion.CASCADE, related_name='aoi', to='animal.areaofinterest')),
                ('species', models.ForeignKey(help_text='Species', on_delete=django.db.models.deletion.CASCADE, related_name='target', to='animal.target')),
            ],
            options={
                'verbose_name': 'Species Location',
                'verbose_name_plural': 'Species Locations',
            },
        ),
        migrations.RunPython(
            load_species_locations_fixture,
            reverse_code=remove_species_locations_data,
        ),
    ]
