# Generated by Django on 2025-09-16

from django.db import migrations

trigger_sql = """
CREATE TRIGGER adjudicate_trigger_with_confidence
AFTER UPDATE ON animal_annotations
BEGIN
    -- Update when there are 3+ annotations with the same classification
    UPDATE animal_pointsofinterest 
    SET final_classification_id = (
        SELECT classification_id 
        FROM (
            SELECT classification_id, COUNT(*) as count
            FROM animal_annotations
            WHERE poi_id = NEW.poi_id
            GROUP BY classification_id
            HAVING COUNT(*) >= 3
            ORDER BY COUNT(*) DESC
            LIMIT 1
        )
    ),
    final_species_id = (
        SELECT target_id 
        FROM (
            SELECT target_id, COUNT(*) as count
            FROM animal_annotations
            WHERE poi_id = NEW.poi_id 
            AND classification_id = (
                SELECT classification_id 
                FROM animal_annotations
                WHERE poi_id = NEW.poi_id
                GROUP BY classification_id
                HAVING COUNT(*) >= 3
                ORDER BY COUNT(*) DESC
                LIMIT 1
            )
            AND target_id IS NOT NULL
            GROUP BY target_id
            ORDER BY COUNT(*) DESC
            LIMIT 1
        )
    ),
    final_confidence_id = (
        SELECT confidence_id 
        FROM (
            SELECT confidence_id, COUNT(*) as count
            FROM animal_annotations
            WHERE poi_id = NEW.poi_id 
            AND classification_id = (
                SELECT classification_id 
                FROM animal_annotations
                WHERE poi_id = NEW.poi_id
                GROUP BY classification_id
                HAVING COUNT(*) >= 3
                ORDER BY COUNT(*) DESC
                LIMIT 1
            )
            AND confidence_id IS NOT NULL
            GROUP BY confidence_id
            ORDER BY COUNT(*) DESC
            LIMIT 1
        )
    ),
    final_review_date = date('now')
    WHERE id = NEW.poi_id
    AND EXISTS (
        SELECT 1
        FROM animal_annotations
        WHERE poi_id = NEW.poi_id
        GROUP BY classification_id
        HAVING COUNT(*) >= 3
        LIMIT 1
    );
END;
"""

revert_sql = """
DROP TRIGGER IF EXISTS adjudicate_trigger_with_confidence;
-- Recreate the old trigger
CREATE TRIGGER adjudicate_trigger
AFTER UPDATE ON animal_annotations
BEGIN
    UPDATE animal_pointsofinterest 
    SET final_classification_id = (
        SELECT classification_id 
        FROM (
            SELECT classification_id, COUNT(*) as count
            FROM animal_annotations
            WHERE poi_id = NEW.poi_id
            GROUP BY classification_id
            HAVING COUNT(*) >= 3
            LIMIT 1
        )
    ),
    final_review_date = date('now')
    WHERE id = NEW.poi_id
    AND EXISTS (
        SELECT 1
        FROM animal_annotations
        WHERE poi_id = NEW.poi_id
        GROUP BY classification_id
        HAVING COUNT(*) >= 3
        LIMIT 1
    );
END;
"""

drop_old_trigger_sql = """
DROP TRIGGER IF EXISTS adjudicate_trigger;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0017_webauthnchallenge_webauthncredential'),
    ]

    operations = [
        # First drop the old trigger
        migrations.RunSQL(drop_old_trigger_sql, reverse_sql=""),
        # Then create the new trigger with confidence support
        migrations.RunSQL(trigger_sql, reverse_sql=revert_sql),
    ]
