# Generated by Django 5.2.6 on 2025-09-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0018_update_adjudicate_trigger_with_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.confidence'),
        ),
    ]
