# Generated by Django 5.2.3 on 2026-03-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_pointsofinterest_final_confidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animal.classification'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.confidence'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.target'),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classification',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Group name for categorizing classifications', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat_order', to='animal.category'),
        ),
        migrations.AlterField(
            model_name='fishnet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.project'),
        ),
        migrations.AlterField(
            model_name='fishnetreviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='final_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.classification'),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='final_confidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.confidence'),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='final_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.target'),
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='animal.project'),
        ),
        migrations.AlterField(
            model_name='projectaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animal.project'),
        ),
        migrations.AlterField(
            model_name='projectaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
