# Generated by Django 5.2.3 on 2026-03-05 20:07
# Manually edited: fix corrupt geometry row before AlterField table rebuild.
#
# GAIFAGP-530 — Enforce NOT NULL on PointsOfInterest.project_id
#
# Django's AlterField on SQLite triggers a full table rebuild. SpatiaLite
# enforces geometry constraints (SRID, type) on INSERT into the new table.
# One row has a corrupt geometry blob (SRID=None, GeometryType=None) that
# fails the constraint check. The RunSQL step NULLs out unrecognizable
# geometry blobs before the rebuild. See also GAIFAGP-523.

import django.db.models.deletion
from django.db import migrations, models


def verify_no_null_projects(apps, schema_editor):
    """Guard: abort migration if any POIs have NULL project_id."""
    PointsOfInterest = apps.get_model('animal', 'PointsOfInterest')
    null_count = PointsOfInterest.objects.filter(project__isnull=True).count()
    if null_count > 0:
        raise ValueError(
            f"Cannot enforce NOT NULL on project_id: {null_count} POIs have "
            f"NULL project_id. Backfill required before this migration can proceed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0020_alter_annotations_classification_and_more'),
    ]

    operations = [
        migrations.RunPython(verify_no_null_projects, migrations.RunPython.noop),
        # NULL out corrupt geometry data before table rebuild.
        # POI 3235 has empty string '' in point column — not valid geometry.
        # ST_SRID() doesn't catch empty strings, so check both cases.
        # Without this, the table rebuild fails with:
        #   "new__animal_pointsofinterest.point violates Geometry constraint"
        # See GAIFAGP-523.
        migrations.RunSQL(
            sql="UPDATE animal_pointsofinterest SET point = NULL WHERE typeof(point) = 'text' OR (point IS NOT NULL AND ST_SRID(point) IS NULL);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='pointsofinterest',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='animal.project',
            ),
        ),
    ]
