# Generated by Django 5.2.3 on 2026-03-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0021_alter_pointsofinterest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='value',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='confidence',
            name='value',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='value',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='species_locations',
            unique_together={('aoi', 'species')},
        ),
    ]
