# Generated by Django 5.2.3 on 2026-03-09 20:56

import django.contrib.gis.db.models.fields
from django.db import migrations


def verify_no_null_geometry(apps, schema_editor):
    POI = apps.get_model('animal', 'PointsOfInterest')
    POI.objects.filter(id=3235).delete()
    null_count = POI.objects.filter(point__isnull=True).count()
    if null_count > 0:
        raise ValueError(
            f"Cannot enforce NOT NULL on point: {null_count} POIs have NULL geometry. "
            f"Run: manage.py poi list --filter=point__isnull=True to identify them."
        )


def apply_not_null(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE animal_pointsofinterest ALTER COLUMN point SET NOT NULL;'
        )


def reverse_not_null(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE animal_pointsofinterest ALTER COLUMN point DROP NOT NULL;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0022_alter_classification_value_alter_confidence_value_and_more'),
    ]

    operations = [
        migrations.RunPython(verify_no_null_geometry, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='pointsofinterest',
                    name='point',
                    field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
            ],
            database_operations=[
                migrations.RunPython(apply_not_null, reverse_not_null),
            ],
        ),
    ]
