# Generated by Django 5.2.6 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0024_rebuild_date_image_taken_from_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='final_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
