# Generated by Django 5.2.3 on 2026-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0028_project_zoom_level_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsofinterest',
            name='generation_method',
            field=models.CharField(blank=True, choices=[('automated', 'automated'), ('fishnet', 'fishnet'), ('manual', 'manual')], help_text='How this POI was created: automated (external tool), fishnet (grid scan), or manual (annotator Add Point).', max_length=20, null=True),
        ),
    ]
