# Generated by Django 5.2.3 on 2026-03-13 18:21

from django.db import migrations


def backfill_generation_method(apps, schema_editor):
    POI = apps.get_model('animal', 'PointsOfInterest')
    # Automated: has sample_idx (Caleb's tool output)
    POI.objects.filter(sample_idx__isnull=False).exclude(sample_idx='').update(generation_method='automated')
    # Manual: no sample_idx AND no catalog_id (Add Point UI creation)
    POI.objects.filter(sample_idx__isnull=True, catalog_id__isnull=True).update(generation_method='manual')
    POI.objects.filter(sample_idx='', catalog_id__isnull=True).update(generation_method='manual')


def reverse_backfill(apps, schema_editor):
    POI = apps.get_model('animal', 'PointsOfInterest')
    POI.objects.all().update(generation_method=None)


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0029_add_generation_method'),
    ]

    operations = [
        migrations.RunPython(backfill_generation_method, reverse_backfill),
    ]
