# Generated by Django 6.0.3 on 2026-03-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0032_imageryloadrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imageryloadrequest',
            new_name='animal_imag_project_33c492_idx',
            old_name='animal_image_project_1f2f42_idx',
        ),
        migrations.RenameIndex(
            model_name='imageryloadrequest',
            new_name='animal_imag_status_b721bc_idx',
            old_name='animal_image_status_a91e37_idx',
        ),
    ]
