# Generated by Django 6.0.3 on 2026-04-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0037_stagedimagerygeojsonupload'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stagedimagerygeojsonupload',
            new_name='animal_stag_project_de3021_idx',
            old_name='stageimg_proj_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stagedimagerygeojsonupload',
            new_name='animal_stag_project_3d35c9_idx',
            old_name='stageimg_proj_consumed_idx',
        ),
    ]
