# Generated by Django 6.0.3 on 2026-04-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0037_point_owner_and_fishnet_unique_reviewer'),
        ('animal', '0038_rename_stageimg_proj_created_idx_animal_stag_project_de3021_idx_and_more'),
    ]

    operations = []
